
[[dependencies]]
  branch = "master"
  name = "github.com/knq/jwt"

[[dependencies]]
  branch = "master"
  name = "golang.org/x/net"

[[dependencies]]
  branch = "master"
  name = "google.golang.org/grpc"
